# Generated by Django 5.2.9 on 2026-05-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_offer', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('normal', 'عادي'), ('best_seller', 'الأكثر مبيعاً'), ('featured', 'مميز')], default='normal', max_length=20),
        ),
    ]
